"""Project constants."""

from pathlib import Path

DEFAULT_SEPARATOR = ","
REQUIRED_KEYS = ("bus", "load_mw", "generator_mw")

MAPPING_PATH = Path(__file__).resolve().parent / "config" / "anarede_mapping.json"
GEN_TYPE_MAPPING_PATH = Path(__file__).resolve().parent / "config" / "gen_type_mapping.json"

DLIN_DERIVED_BLOCKS: tuple[str, ...] = (
    "DLIN_TAP",
    "DLIN_PHASE_SHIFT",
    "DLIN_TRANSFORMER",
    "DLIN_SWITCH",
)
DLIN_BRANCH_BLOCKS: tuple[str, ...] = ("DLIN", *DLIN_DERIVED_BLOCKS)
BUS_INTERNAL_GROUP_BLOCKS: tuple[str, ...] = ("DGBT", "DGLT")
SWITCH_IMPEDANCE_MNEMONIC: str = "ZMIN"
DEFAULT_SWITCH_IMPEDANCE_THRESHOLD: float = 0.001

# Component types reported under "Power Flow Information" instead of "Component Information".
POWER_FLOW_COMPONENT_TYPES: tuple[str, ...] = ("PowerFlowOption", "ProgramConstant")
RESULT_COMPONENT_TYPES: tuple[str, ...] = (
    "StatisticResultsInformation",
    "ACBusResults",
    "ACLineResults",
    "LTCTransformerResults",
    "PhaseShiftingTransformerResults",
    "SwitchDeviceResults",
    "StaticVARCompensatorResults",
    "ControllableSeriesCompensatorResults",
    "DCLineResults",
)

SHEET_HEADERS: dict[str, tuple[str, ...]] = {
    "Summary": ("Field", "Value"),
    "Buses": (
        "Bus",
        "Name",
        "Type",
        "Area",
        "InServ",
        "Vm(pu)",
        "Vm(kV)",
        "Va(deg)",
        "Pg(MW)",
        "Qg(MVAr)",
        "Pl(MW)",
        "Ql(MVAr)",
        "Vmin",
        "Vmax",
        "Violation",
        "RepresentativeBus",
        "Collapsed",
    ),
    "Generators": (
        "Bus",
        "Name",
        "Type",
        "Pg(MW)",
        "Qg(MVAr)",
        "Pmax(MW)",
        "Reserve(MW)",
        "Vm(pu)",
        "Va(deg)",
    ),
    "Loads": ("Bus", "Name", "Pl(MW)", "Ql(MVAr)", "Source"),
    "Lines": (
        "Line",
        "From",
        "To",
        "Circuit",
        "R(pu)",
        "X(pu)",
        "B(pu)",
        "Tap",
        "Shift(deg)",
        "Rate(MVA)",
        "MW:From-To",
        "Mvar:From-To",
        "Power Factor:From-To",
        "F:Capac/Inductive",
        "MW:To-From",
        "Mvar:To-From",
        "Power Factor:To-From",
        "T:Capac/Inductive",
        "Loading%",
        "P_loss(MW)",
        "Q_loss(MVAr)",
        "Violation",
    ),
    "Transformers": (
        "Device",
        "From",
        "To",
        "Circuit",
        "R(pu)",
        "X(pu)",
        "Tap",
        "Shift(deg)",
        "Rate(MVA)",
        "MW:From-To",
        "Mvar:From-To",
        "Power Factor:From-To",
        "F:Capac/Inductive",
        "MW:To-From",
        "Mvar:To-From",
        "Power Factor:To-From",
        "T:Capac/Inductive",
        "Loading%",
        "P_loss(MW)",
        "Q_loss(MVAr)",
        "Violation",
    ),
    "LTC": (
        "Device",
        "From",
        "To",
        "Circuit",
        "CtrlBus",
        "Tap",
        "TapMin",
        "TapMax",
        "Vtarget",
        "MW:From-To",
        "Mvar:From-To",
        "Power Factor:From-To",
        "F:Capac/Inductive",
        "MW:To-From",
        "Mvar:To-From",
        "Power Factor:To-From",
        "T:Capac/Inductive",
    ),
    "PST": (
        "Device",
        "From",
        "To",
        "Circuit",
        "CtrlBus",
        "Shift(deg)",
        "ShiftMin(deg)",
        "ShiftMax(deg)",
        "Ptarget(MW)",
        "MW:From-To",
        "Mvar:From-To",
        "Power Factor:From-To",
        "F:Capac/Inductive",
        "MW:To-From",
        "Mvar:To-From",
        "Power Factor:To-From",
        "T:Capac/Inductive",
    ),
    "HVDC": (
        "Bus#",
        "BusName",
        "Volt(pu)",
        "Type",
        "Pole#",
        "Control",
        "P(MW)",
        "Q(MVAr)",
        "Loss(MW)",
        "Vdc(kV)",
        "Idc(pu)",
        "Idc(A)",
        "Alpha(deg)",
        "Mu(deg)",
        "Phi(deg)",
        "Tap",
        "Status",
    ),
    "SVC": (
        "Device",
        "Bus",
        "CtrlBus",
        "Mode",
        "Qsvc(MVAr)",
        "Qmin(MVAr)",
        "Qmax(MVAr)",
        "Residual",
        "State",
    ),
    "CSC": (
        "Device",
        "From",
        "To",
        "Circuit",
        "Mode",
        "X(pu)",
        "Xmin(pu)",
        "Xmax(pu)",
        "MW:From-To",
        "Mvar:From-To",
        "Power Factor:From-To",
        "F:Capac/Inductive",
        "MW:To-From",
        "Mvar:To-From",
        "Power Factor:To-From",
        "T:Capac/Inductive",
        "Status",
    ),
}
