"""Typed model exports and block-to-model registry."""

from __future__ import annotations

from infrasys import Component

from o_grid.models.base import AnaredeComponent, OGridComponent
from o_grid.models.branch import (
    ACBranch,
    ACLine,
    Branch,
    ControllableSeriesCompensator,
    DCLine,
    FlowMonitoringCircuit,
    FromToToFrom,
    Line,
    LineShunt,
    LTCTransformer,
    MinMax,
    PhaseShiftingTransformer,
    SeriesCompensator,
    SwitchDevice,
    TapChangingTransformer,
    TransferFunctionCircuit,
    TransformerDevice,
)
from o_grid.models.case import CaseTitle
from o_grid.models.control import (
    ConverterControl,
    ConverterStation,
    DCLineData,
    PowerFlowOption,
    ProgramConstant,
    TapTransformerControl,
    TransferFunctionConstraint,
)
from o_grid.models.enums import (
    ACBusTypes,
    BankControllerControlType,
    CircuitState,
    ConverterControlSlack,
    ConverterControlType,
    ConverterMode,
    CSCControlMode,
    DCBusPolarity,
    DCBusType,
    GenType,
    HighVArMode,
    InverterControlMode,
    OptionState,
    ShuntControlMode,
    SVCControlMode,
    TransformerManeuverable,
    VoltageMonitoringCondition,
)
from o_grid.models.generators import (
    Generator,
    GeneratorDispatchData,
    IndividualizedGeneratorGroup,
    ReactiveCompensator,
    StaticVARCompensator,
)
from o_grid.models.load import (
    BankController,
    BusShuntBank,
    IndividualizedLoad,
    LineShuntBank,
    ShuntBank,
)
from o_grid.models.topology import (
    ACBus,
    Arc,
    Area,
    AreaInterchange,
    Bus,
    BusVoltageMonitoring,
    DCBus,
    Topology,
    VoltageBaseGroup,
    VoltageLimitGroup,
    VoltageMonitoringSelection,
)

BLOCK_BASE_CLASSES: dict[str, type[Component]] = {
    "TITU": CaseTitle,
    "DOPC": PowerFlowOption,
    "DCTE": ProgramConstant,
    "DBAR": ACBus,
    "DLIN": ACLine,
    "DGLT": VoltageLimitGroup,
    "DGBT": VoltageBaseGroup,
    "DARE": AreaInterchange,
    "DBSH": BankController,
    "DBSH_BANK": ShuntBank,
    "DCAI": IndividualizedLoad,
    "DCER": StaticVARCompensator,
    "DCSC": ControllableSeriesCompensator,
    "DCTR": TapTransformerControl,
    "DGEI": IndividualizedGeneratorGroup,
    "DGER": Generator,
    "DCLI": DCLine,
    "DCBA": DCBus,
    "DCCV": ConverterControl,
    "DCNV": ConverterStation,
    "DELO": DCLineData,
    "DSHL": LineShunt,
    "DMFL_CIRC": FlowMonitoringCircuit,
    "DMTE": VoltageMonitoringSelection,
    "DTPF": TransferFunctionConstraint,
    "DTPF_CIRC": TransferFunctionCircuit,
    "DLIN_TAP": LTCTransformer,
    "DLIN_PHASE_SHIFT": PhaseShiftingTransformer,
    "DLIN_TRANSFORMER": TransformerDevice,
    "DLIN_SWITCH": SwitchDevice,
}

__all__ = [
    "ACBusTypes",
    "BankControllerControlType",
    "DCBusPolarity",
    "DCBusType",
    "ConverterControlType",
    "ConverterControlSlack",
    "ConverterMode",
    "InverterControlMode",
    "CSCControlMode",
    "ShuntControlMode",
    "OptionState",
    "CircuitState",
    "HighVArMode",
    "GenType",
    "ACBus",
    "ACBranch",
    "ACLine",
    "AnaredeComponent",
    "Arc",
    "Area",
    "BLOCK_BASE_CLASSES",
    "Branch",
    "Bus",
    "BusVoltageMonitoring",
    "BankController",
    "BusShuntBank",
    "CaseTitle",
    "AreaInterchange",
    "ConverterControl",
    "ConverterStation",
    "IndividualizedLoad",
    "DCBus",
    "DCLine",
    "DCLineData",
    "GeneratorDispatchData",
    "Generator",
    "IndividualizedGeneratorGroup",
    "FromToToFrom",
    "FlowMonitoringCircuit",
    "LineShunt",
    "LineShuntBank",
    "Line",
    "MinMax",
    "OGridComponent",
    "PhaseShiftingTransformer",
    "PowerFlowOption",
    "ProgramConstant",
    "ReactiveCompensator",
    "StaticVARCompensator",
    "SVCControlMode",
    "SeriesCompensator",
    "ControllableSeriesCompensator",
    "ShuntBank",
    "SwitchDevice",
    "TapTransformerControl",
    "LTCTransformer",
    "TapChangingTransformer",
    "Topology",
    "TransferFunctionCircuit",
    "TransformerDevice",
    "TransferFunctionConstraint",
    "VoltageBaseGroup",
    "VoltageLimitGroup",
    "TransformerManeuverable",
    "VoltageMonitoringCondition",
    "VoltageMonitoringSelection",
]
