"""Typed model exports and block-to-model registry."""

from __future__ import annotations

from o_grid.models.base import AnaredeComponent, OGridComponent
from o_grid.models.branch import (
    ACBranch,
    ACLine,
    Branch,
    ControllableSeriesCompensator,
    DCLink,
    FromToToFrom,
    Line,
    MinMax,
    PhaseShiftingTransformer,
    SeriesCompensator,
    ShuntLine,
    TapChangingTransformer,
    TapTransformer,
    TransferFunctionCircuit,
)
from o_grid.models.case import CaseTitle
from o_grid.models.control import (
    ConverterControl,
    ConverterStation,
    DCLinkOwner,
    PowerFlowOption,
    ProgramConstant,
    TapTransformerControl,
    TransferFunctionConstraint,
)
from o_grid.models.enums import ACBusTypes, CSCControlMode, SVCControlMode
from o_grid.models.generators import (
    GeneratorDispatchData,
    ReactiveCompensator,
    StaticVARCompensator,
)
from o_grid.models.load import (
    BusShunt,
    CurrentInjectionLoad,
    LineShunt,
    ShuntBank,
    ShuntCompensator,
)
from o_grid.models.topology import (
    ACBus,
    Arc,
    Area,
    AreaInterchange,
    Bus,
    DCBus,
    Topology,
    VoltageBaseGroup,
    VoltageLimitGroup,
)

BLOCK_BASE_CLASSES: dict[str, type[AnaredeComponent]] = {
    "TITU": CaseTitle,
    "DOPC": PowerFlowOption,
    "DCTE": ProgramConstant,
    "DBAR": ACBus,
    "DLIN": ACLine,
    "DGLT": VoltageLimitGroup,
    "DGBT": VoltageBaseGroup,
    "DARE": AreaInterchange,
    "DBSH": BusShunt,
    "DBSH_BANK": LineShunt,
    "DCAI": CurrentInjectionLoad,
    "DCER": StaticVARCompensator,
    "DCSC": ControllableSeriesCompensator,
    "DCTR": TapTransformerControl,
    "DGER": GeneratorDispatchData,
    "DCLI": DCLink,
    "DCBA": DCBus,
    "DCCV": ConverterControl,
    "DCNV": ConverterStation,
    "DELO": DCLinkOwner,
    "DSHL": ShuntLine,
    "DTPF": TransferFunctionConstraint,
    "DTPF_CIRC": TransferFunctionCircuit,
    "DLIN_TAP": TapTransformer,
    "DLIN_PHASE_SHIFT": PhaseShiftingTransformer,
}

__all__ = [
    "ACBusTypes",
    "CSCControlMode",
    "ACBus",
    "ACBranch",
    "ACLine",
    "AnaredeComponent",
    "Arc",
    "Area",
    "BLOCK_BASE_CLASSES",
    "Branch",
    "Bus",
    "BusShunt",
    "CaseTitle",
    "AreaInterchange",
    "ConverterControl",
    "ConverterStation",
    "CurrentInjectionLoad",
    "DCBus",
    "DCLink",
    "DCLinkOwner",
    "GeneratorDispatchData",
    "FromToToFrom",
    "LineShunt",
    "Line",
    "MinMax",
    "OGridComponent",
    "PhaseShiftingTransformer",
    "PowerFlowOption",
    "ProgramConstant",
    "ReactiveCompensator",
    "StaticVARCompensator",
    "SVCControlMode",
    "SeriesCompensator",
    "ControllableSeriesCompensator",
    "ShuntBank",
    "ShuntCompensator",
    "ShuntLine",
    "TapTransformerControl",
    "TapTransformer",
    "TapChangingTransformer",
    "Topology",
    "TransferFunctionCircuit",
    "TransferFunctionConstraint",
    "VoltageBaseGroup",
    "VoltageLimitGroup",
]
