"""Generator and reactive equipment models."""

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from o_grid.models.base import AnaredeComponent, ParsedScalar


class GeneratorDispatchData(AnaredeComponent):
    """Generator dispatch and participation data."""

    armature_service_factor: Annotated[
        ParsedScalar,
        Field(
            description="Armature current service factor, in %",
            json_schema_extra={"units": "%"},
        ),
    ] = None
    load_angle: Annotated[
        ParsedScalar,
        Field(
            description="Maximum load angle (0.0 – 85.0), in degrees.",
            json_schema_extra={"units": "degrees"},
        ),
    ] = None
    machine_reactance: Annotated[
        ParsedScalar,
        Field(
            description="Machine Reactance, in %.",
            json_schema_extra={"units": "%"},
        ),
    ] = None
    max_active_generation: Annotated[
        ParsedScalar,
        Field(
            description="Maximum active power generation limit value at the bus, in MW.",
            json_schema_extra={"units": "MW"},
        ),
    ] = 99999.0
    min_active_generation: Annotated[
        ParsedScalar,
        Field(
            description="Minimum active power generation limit value at the bus, in MW.",
            json_schema_extra={"units": "MW"},
        ),
    ] = 0.0
    nominal_apparent_power: Annotated[
        ParsedScalar,
        Field(
            description="Machine nominal apparent power, in MVA",
            json_schema_extra={"units": "MVA"},
        ),
    ] = None
    nominal_power_factor: Annotated[
        ParsedScalar,
        Field(
            description="Machine Nominal Power Factor.",
        ),
    ] = None
    number: Annotated[
        ParsedScalar,
        Field(
            description="Bus number, as defined in the Number field of the DBAR Execution Code.",
        ),
    ] = None
    operation: Annotated[
        ParsedScalar,
        Field(
            description=(
                "A or 0 - addition of active power generation limits and participation "
                "factors data\\nM or 2 - modification of active power generation limits "
                "and participation factors data"
            ),
        ),
    ] = 'A'
    participation_factor: Annotated[
        ParsedScalar,
        Field(
            description=(
                "Generation bus participation factor value, in %. The active power "
                "interchange error of each area is distributed among the area generation "
                "buses, proportionally to each one's participation factor, observing the "
                "respective minimum and maximum active power generation limits."
            ),
            json_schema_extra={"units": "%"},
        ),
    ] = 0.0
    remote_control_participation_factor: Annotated[
        ParsedScalar,
        Field(
            description=(
                "Generator participation factor in the amount of reactive power needed "
                "for remote bus voltage control in %."
            ),
            json_schema_extra={"units": "%"},
        ),
    ] = 100.0
    rotor_service_factor: Annotated[
        ParsedScalar,
        Field(
            description="Rotor current service factor, in %",
            json_schema_extra={"units": "%"},
        ),
    ] = None

class ReactiveCompensator(AnaredeComponent):
    """Reactive compensation element model."""

    bus: Annotated[
        ParsedScalar,
        Field(
            description="Bus Number as defined in the Number field of the DBAR Execution Code.",
        ),
    ] = None
    control_mode: Annotated[
        ParsedScalar,
        Field(
            description=(
                "P – Control by power generated by the SVC.\\nI – Control by current "
                "injected by the SVC."
            ),
        ),
    ] = 'I'
    controlled_bus: Annotated[
        ParsedScalar,
        Field(
            description=(
                "Bus Number as defined in the Number field of the DBAR Execution Code "
                "whose voltage will be controlled by the value defined in the Voltage "
                "field of the DBAR Execution Code."
            ),
        ),
    ] = None
    group: Annotated[
        ParsedScalar,
        Field(
            description=(
                "Identification number of the static reactive compensator group. One or "
                "more SVC groups can be connected to a bus and a group can be composed of "
                "one or more static compensators."
            ),
        ),
    ] = None
    max_reactive_generation: Annotated[
        ParsedScalar,
        Field(
            description=(
                "Maximum reactive power generation limit value, in Mvar, that defines the "
                "limits of the linear part of the Static Reactive Compensator model "
                "control curve."
            ),
        ),
    ] = None
    min_reactive_generation: Annotated[
        ParsedScalar,
        Field(
            description=(
                "Minimum reactive power generation limit value, in Mvar, that defines the "
                "limits of the linear part of the Static Reactive Compensator model "
                "control curve."
            ),
        ),
    ] = None
    operation: Annotated[
        ParsedScalar,
        Field(
            description=(
                "A or 0 - static reactive compensator data addition.\\nE or 1 - static "
                "reactive compensator data elimination.\\nM or 2 - static reactive "
                "compensator data modification."
            ),
        ),
    ] = 'A'
    reactive_generation: Annotated[
        ParsedScalar,
        Field(
            description="Current reactive power generation value.",
        ),
    ] = None
    slope: Annotated[
        ParsedScalar,
        Field(
            description=(
                "Slope value of the line that defines the linear part of the Static "
                "Reactive Compensator model control curve, in %."
            ),
            json_schema_extra={"units": "%"},
        ),
    ] = None
    state: Annotated[
        ParsedScalar,
        Field(
            description=(
                "L if the compensator group is in operation (connected).\\nD if the "
                "compensator group is out of operation (disconnected)."
            ),
        ),
    ] = 'L'
    units: Annotated[
        ParsedScalar,
        Field(
            description="Number of equal units that compose the SVC group.",
        ),
    ] = None
