#include "../headers/definitions.h"

const double kPi = 3.14159265358979323846;
const double TOLERANCE = 1e-12;
const double DISPLAY_TOLERANCE = 1e-9;
const double MIN_DENOMINATOR = 1e-6;
const double SPARSE_FALLBACK_TOLERANCE = 1e-10;
const double LINE_SEARCH_MIN_ALPHA = 1e-4;
const double DEFAULT_POWER_FLOW_TOLERANCE = 2e-5;
const double AC_ACTIVE_POWER_TOLERANCE_MW = 0.1;
const double AC_REACTIVE_POWER_TOLERANCE_MVAR = 0.1;
const double VLIM_REACTIVE_START_TOLERANCE = 2e-5;
const double VLIM_CONTROL_TOLERANCE = 1e-4;
const double REACTIVE_LIMIT_TOLERANCE_MVAR = 0.1;
const double AREA_INTERCHANGE_TOLERANCE_MW = 0.1;
const double VOLTAGE_DIVERGENCE_MIN_PU = 0.4;
const double VOLTAGE_DIVERGENCE_MAX_PU = 2.0;
const double LCC_INTERFACE_ACTIVE_TOLERANCE_MW = 0.1;
const double LCC_INTERFACE_REACTIVE_TOLERANCE_MVAR = 0.1;
const double LCC_OUTER_TOLERANCE_MVAR = 5e-2;
const double LOW_IMPEDANCE_REDUCTION_TOLERANCE = 2.000001e-4;
const double ANAREDE_JUMPER_REDUCTION_TOLERANCE = 1.05e-3;
const double ANAREDE_JUMPER_FLOW_MARGIN = 1.25;
